# Generated by Django 3.0.8 on 2022-04-02 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identification for the campaign', max_length=250)),
                ('emails', models.TextField(blank=True, max_length=25000, null=True)),
                ('from_email', models.CharField(default='EasyReach.Today <sambadnilmani085@gmail.com>', help_text="Ensure that it's approved on SES. Format is what's put above as default", max_length=100)),
                ('subject', models.CharField(blank=True, help_text='Max 200 characters', max_length=200, null=True)),
                ('body_html', models.TextField(blank=True, help_text='Put full HTML', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='one_off_emails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'One Off Email Outreach',
                'verbose_name_plural': 'One Off Email Outreaches',
            },
        ),
        migrations.CreateModel(
            name='UserVerificationCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Verification Code',
                'verbose_name_plural': 'User Verification Codes',
            },
        ),
    ]
