# Generated by Django 3.0.8 on 2021-12-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('ref_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('ads_url', models.URLField(blank=True, null=True)),
                ('border_height', models.IntegerField(default=200)),
                ('border_width', models.IntegerField(default=100)),
                ('img_height', models.IntegerField(default=180)),
                ('img_width', models.IntegerField(default=990)),
                ('border_color', models.CharField(choices=[('RED', 'red'), ('WHITE', 'white'), ('BLUE', 'blue')], default='RED', max_length=50)),
                ('position', models.CharField(choices=[('TOP', 'top'), ('MIDDLE', 'middle'), ('BUTTOM', 'buttom')], default='TOP', max_length=50)),
                ('body', models.TextField(blank=True, max_length=9999999, null=True)),
                ('visibility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
