# Generated by Django 3.0.8 on 2021-12-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SponsorAds',
            new_name='SponsorAd',
        ),
    ]
