# Generated by Django 3.0.8 on 2021-12-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20211210_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorad',
            name='border_width',
            field=models.IntegerField(default=1000),
        ),
    ]
