# Generated by Django 3.0.8 on 2021-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211210_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorad',
            name='Test_demo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
