# Generated by Django 3.1.7 on 2022-01-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemap',
            name='lastmod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='ampurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
