# Generated by Django 3.2 on 2022-05-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
