# Generated by Django 4.0 on 2021-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(help_text='Identification for the campaign', max_length=250)),
                ('question_html', models.TextField(blank=True, help_text='Put full HTML', null=True)),
                ('label', models.CharField(default='EasyReach.Today <sambadnilmani085@gmail.com>', help_text="Ensure that it's approved on SES. Format is what's put above as default", max_length=100)),
                ('answer', models.CharField(default='EasyReach.Today <sambadnilmani085@gmail.com>', help_text="Ensure that it's approved on SES. Format is what's put above as default", max_length=100)),
                ('emails', models.TextField(blank=True, max_length=25000, null=True)),
                ('from_email', models.CharField(default='EasyReach.Today <sambadnilmani085@gmail.com>', help_text="Ensure that it's approved on SES. Format is what's put above as default", max_length=100)),
                ('subject', models.CharField(blank=True, help_text='Max 200 characters', max_length=200, null=True)),
                ('body_html', models.TextField(blank=True, help_text='Put full HTML', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='one_off_emails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
