# Generated by Django 3.0.8 on 2022-04-02 21:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(help_text='Identification for the campaign', max_length=250)),
                ('question_html', models.TextField(blank=True, help_text='Put full HTML', null=True)),
                ('label', models.CharField(default='EasyReach.Today <sambadnilmani085@gmail.com>', help_text="Ensure that it's approved on SES. Format is what's put above as default", max_length=100)),
                ('answer', models.CharField(default='EasyReach.Today <sambadnilmani085@gmail.com>', help_text="Ensure that it's approved on SES. Format is what's put above as default", max_length=100)),
                ('emails', models.TextField(blank=True, max_length=25000, null=True)),
                ('from_email', models.CharField(default='EasyReach.Today <sambadnilmani085@gmail.com>', help_text="Ensure that it's approved on SES. Format is what's put above as default", max_length=100)),
                ('subject', models.CharField(blank=True, help_text='Max 200 characters', max_length=200, null=True)),
                ('body_html', models.TextField(blank=True, help_text='Put full HTML', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='one_off_emails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mobile', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('principal_sign_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('logo_of_school', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_date_of_birth', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('owner_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_city', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
