# Generated by Django 3.1.7 on 2022-01-23 01:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mobile', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('principal_sign_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('logo_of_school', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_date_of_birth', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('owner_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_city', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
